name: Python applications

on:
  push:
   branches: [ celery_master ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: paraschheda
          password: chheda9498
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: paraschheda/celery
      -
        name: Deploy to SSH
        uses: appleboy/ssh-action@master
        with:
          host: 5.161.95.212
          username: root
          password: munkybomb
          port: 22
          script: |
            cd /home/dockertest
            sh init.sh